# Generated by Django 5.0.4 on 2024-04-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_order_anthonystudent_order_customer_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='anthonystudent',
        ),
        migrations.CreateModel(
            name='AnthonyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
                ('anthonystudent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.anthonystudent')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product')),
            ],
        ),
    ]
