# Generated by Django 5.0.4 on 2024-04-13 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_order_anthonystudent_anthonyorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnthonyOffense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major')], max_length=200, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
                ('anthonystudent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.anthonystudent')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product')),
            ],
        ),
        migrations.DeleteModel(
            name='AnthonyOrder',
        ),
    ]
