# Generated by Django 5.0.4 on 2024-04-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_anthonyoffense_delete_anthonyorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anthonyoffense',
            old_name='anthonystudent',
            new_name='name',
        ),
    ]
