# Generated by Django 5.0.4 on 2024-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_anthonystudent_anthonyoffense_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='anthonystudent',
            name='guardian',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
