# Generated by Django 5.0.4 on 2024-04-14 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_offense_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anthonyoffense',
            old_name='offense',
            new_name='product',
        ),
    ]
