# Generated by Django 5.0.4 on 2024-04-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_offense_anthonyoffense_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anthonyoffense',
            old_name='product',
            new_name='offense',
        ),
    ]
