# Generated by Django 5.0.4 on 2024-04-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_product_anthonyoffense_offense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anthonyoffense',
            old_name='offense',
            new_name='product',
        ),
    ]
