# Generated by Django 5.0.4 on 2024-04-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_teresastudent_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneoffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='anthonyoffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='berchmanoffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='boscooffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='charlesoffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='faustinaoffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='josephoffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='martinoffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='maryoffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pauloffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ritaoffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='roseoffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='teresaoffense',
            name='action',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
