# Generated by Django 5.0.4 on 2024-04-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_anneoffense_action_anthonyoffense_action_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anneoffense',
            old_name='action',
            new_name='action_given',
        ),
        migrations.RenameField(
            model_name='anthonyoffense',
            old_name='action',
            new_name='action_given',
        ),
        migrations.RenameField(
            model_name='berchmanoffense',
            old_name='action',
            new_name='action_given',
        ),
        migrations.RenameField(
            model_name='boscooffense',
            old_name='action',
            new_name='action_given',
        ),
        migrations.RenameField(
            model_name='charlesoffense',
            old_name='action',
            new_name='action_given',
        ),
        migrations.RenameField(
            model_name='faustinaoffense',
            old_name='action',
            new_name='action_given',
        ),
        migrations.RenameField(
            model_name='josephoffense',
            old_name='action',
            new_name='action_given',
        ),
        migrations.RenameField(
            model_name='martinoffense',
            old_name='action',
            new_name='action_given',
        ),
        migrations.RenameField(
            model_name='maryoffense',
            old_name='action',
            new_name='action_given',
        ),
        migrations.RenameField(
            model_name='pauloffense',
            old_name='action',
            new_name='action_given',
        ),
        migrations.RenameField(
            model_name='ritaoffense',
            old_name='action',
            new_name='action_given',
        ),
        migrations.RenameField(
            model_name='roseoffense',
            old_name='action',
            new_name='action_given',
        ),
        migrations.RenameField(
            model_name='teresaoffense',
            old_name='action',
            new_name='action_given',
        ),
    ]
